Module2 task1
htmlacademy-vue/502211-pizza-1 pull request #2
Opened 2022-04-21 18:47 UTC by poly-titova

2022-04-21 19:22 UTC, xyz27900 commented on src/frontend/src/views/Index.vue
> +        <BuilderIngredintsSelector
Опечатка в наименовании компонента здесь

2022-04-21 19:39 UTC, xyz27900 requested changes
Нужно добавить обработку всех событий

Согласно заданию, 
> Объект пиццы для добавления в корзину находится в родительском компоненте и собирает необходимые параметры.

Поэтому нужно сделать так, чтобы страница была не статической, а все собиралось в один объект внутри родителя

2023-01-20 15:10 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +        const updatedIngredient = { ...this.ingredient };
Как то сложно можно было бы и не создавать новый объект 
`this.$emit("minusButtonClick", this.ingredient.amount - 1)`

2023-01-20 15:10 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +        const updatedIngredient = { ...this.ingredient };
Так же можно было бы и plusButtonClickHandler сделать

2023-01-20 15:10 UTC, enotke commented on src/frontend/src/common/components/RadioButton.vue
> +      return this.itemName === ITEMS_INPUT_DATA.SAUCE.ITEM_NAME
![image](https://user-images.githubusercontent.com/88033634/213728611-2b30355f-b863-4928-88f6-bc83530c6dcb.png)

2023-01-20 15:10 UTC, enotke commented on src/frontend/src/common/components/RadioButton.vue
> +      return this.itemName === ITEMS_INPUT_DATA.SAUCE.ITEM_NAME
Посмотри как в изначальной верстке это выглядит

2023-01-20 15:10 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +        const updatedIngredient = { ...this.ingredient };
Или можно было бы обойтись одним counterChangeHandler

2023-01-20 15:10 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +        const updatedIngredient = { ...this.ingredient };
`this.counterChangeHandler(this.ingredient.amount - 1)`

2023-01-20 15:10 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +      this.$emit("blur", ingredientTemplate);
И почему blur? Лучше использовать change или update

2023-01-20 15:10 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +            :class="getPizzaFillingClass(item)"
Тут немного другая логика. Если например выбрано два одинаковых ингредиента, то должно быть два блока. Один pizza__filling--mushrooms, и ещё один pizza__filling--mushrooms pizza__filling--second. Если три одинаковых, то 3 блока

2023-01-20 15:10 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +            :class="getPizzaFillingClass(item)"
если два одинаковых, то должно быть вот так
`<div class=pizza__filling--tomatoes /> <div class=pizza__filling--tomatoes pizza__filling--second />`
Если три
`<div class=pizza__filling--tomatoes /> <div class=pizza__filling--tomatoes pizza__filling--second  /> <div class=pizza__filling--tomatoes pizza__filling--third  />`

2023-01-20 15:10 UTC, enotke commented on src/frontend/src/views/Index.vue
> +      const ingredients = { ...this.selectedIngredients };
Вообще можно например хранить в виде `{ingredientName: amount}` и тогда можно будет просто через `Vue.$set` присваивать новое значение. И тогда можно будет сделать один метод updateIngredientCount, а не три

2023-01-21 11:53 UTC, poly-titova commented on src/frontend/src/common/components/RadioButton.vue
> +      return this.itemName === ITEMS_INPUT_DATA.SAUCE.ITEM_NAME
Не поняла, что не так?

2023-01-21 13:04 UTC, poly-titova commented on src/frontend/src/views/Index.vue
> +      const ingredients = { ...this.selectedIngredients };
так можно оставить раз работает?

2023-01-21 13:10 UTC, enotke commented on src/frontend/src/common/components/RadioButton.vue
> +      return this.itemName === ITEMS_INPUT_DATA.SAUCE.ITEM_NAME
Запусти пример верстки из папки template

2023-01-21 13:10 UTC, enotke commented on src/frontend/src/common/components/RadioButton.vue
> +      return this.itemName === ITEMS_INPUT_DATA.SAUCE.ITEM_NAME
![image](https://user-images.githubusercontent.com/88033634/213868313-c2dfba29-9936-4b0b-87cd-2c5317e6b555.png)
Должно быть вот так

2023-01-21 13:23 UTC, enotke commented on src/frontend/src/views/Index.vue
> +      const ingredients = { ...this.selectedIngredients };
Можно и так

2023-01-21 14:01 UTC, poly-titova commented on src/frontend/src/common/components/ItemCounter.vue
> +        const updatedIngredient = { ...this.ingredient };
![image](https://user-images.githubusercontent.com/17946491/213870296-bbb9bb95-a04e-4cf2-8173-19a045db087f.png)
не получается так, nan и минус не работает

2023-01-24 15:24 UTC, merged