Module4 task1
htmlacademy-vue/502211-pizza-1 pull request #4
Opened 2023-03-20 17:46 UTC by poly-titova

2023-03-21 13:23 UTC, S-le requested changes
Ты молодец! Ты постаралась и это заметно. Эта и следующая темы самые сложные, но и самые важные. Поэтому не воспринимай это как неудачу. Это часть учебного процесса. Нам с тобой важно разобраться в этой теме, а не просто сделать для галочки.

Мне показалось, что ты в какой-то момент просто запуталась в большом количестве модулей. Я постарался написать комментарии к коду. Если что-то не понятно, то можешь написать мне. Но я очень рекомендую тебе взять голосовую консультацию. Так мы сможем эффективно проработать код и закрыть все пробелы.

Постарайся проработать тему еще раз. Я верю, что у тебя все получится.

2023-03-21 13:23 UTC, S-le commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +      <RouterLink to="/cart">{{ orderPrice }} ₽</RouterLink>
Неверно указано название переменной.

2023-03-21 13:23 UTC, S-le commented on src/frontend/src/store/modules/auth.store.js
> +export const resetState = () => ({
Желательно еще подумать над названием этой функции. `resetState` больше подходит _action_ или _mutation_, которые после вызова изменят _state_ до начального состояния. Это не ошибка, просто рекомендация по нэймингу.

2023-03-21 13:23 UTC, S-le commented on src/frontend/src/store/modules/auth.store.js
> +  isAuthorized: false,
Если пользователь не авторизован, то `user` будет иметь значение **null**. Следовательно, можно создать getter `isAuthorizes` и в нем проверять авторизацию `state.user !== null`. Это избавит от постоянных вызовов `CHANGE_AUTH_STATUS`.

2023-03-21 13:23 UTC, S-le commented on src/frontend/src/store/modules/builder.store.js
> +    });
В *state* свойство `pizzas` это массив. Но если заглянуть в *piazza.json*, то там объект. Этот объект содержит информацию для конструктора пиццы. 
Послу мутации `FETCH_PIZZAS` `state.pizzas` присваивается значение pizzas, после чего `state.pizzas` уже не массив, а объект.
Также непонятно для чего нужно свойство `module` и `entity`.

2023-03-21 13:23 UTC, S-le commented on src/frontend/src/store/modules/builder.store.js
> +    const multiplier = state.pizzas.sizes.find(
Если посмотрим код выше:

```
export const resetState = () => ({
  pizzas: [],
  ...
```

`pizzas` - это массив.

Если посмотри код ниже:

```
commit(FETCH_PIZZAS, {
    module: null,
    entity: "pizzas",
    value: pizzas,
});

...

[FETCH_PIZZAS](state, items) {
    state.pizzas = items;
}
```

`pizzas` - это следующий объект:
```
{ 
    module: null, 
    entity: "pizzas", 
    value: {
        dough: [...],
        ingredients: [...],
        sauces: [...],
        sizes: [...],
    }
}
```

Тебе надо внимательно разобраться со структурой данных. Из-за этого большая путаница во всем проекте. В компоненте `BuilderDoughSelector.vue` есть вычисляемое свойство:
```
dough() {
    return this.pizzas.dough;
}
```

2023-03-21 13:23 UTC, S-le commented on src/frontend/src/common/components/AppDrop.vue
> +    }),
`AppDrop` - это HOC. Его можно назвать "глупым" компонентом. Он ничего не меняет и не наследует поведение оборачиваемого компонента. Можно сравнить его с чистой функцией. Он совершает действие и возвращает результат без побочных эффектов. Поэтому рекомендую откатить изменения всего компонента.

2023-03-21 13:23 UTC, S-le commented on src/frontend/src/common/components/FormInput.vue
> +    },
Желательно добавить валидатор. У аттрибута `type` есть [разные значения](https://developer.mozilla.org/ru/docs/Web/HTML/Element/input#attr-type) и не все подходят этому компоненту.

2023-03-21 13:23 UTC, S-le commented on src/frontend/src/common/components/FormInput.vue
> +    },
Интересное решение. Еще можно использовать [содержимое слота по умолчанию](https://ru.vuejs.org/v2/guide/components-slots.html#%D0%A1%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B8%D0%BC%D0%BE%D0%B5-%D1%81%D0%BB%D0%BE%D1%82%D0%B0-%D0%BF%D0%BE-%D1%83%D0%BC%D0%BE%D0%BB%D1%87%D0%B0%D0%BD%D0%B8%D1%8E)

2023-03-21 13:23 UTC, S-le commented on src/frontend/src/common/components/ItemCounter.vue
> +      refreshKey: 0,
Какое назначение у этого свойства?

2023-03-21 13:23 UTC, S-le commented on src/frontend/src/common/components/SidebarMenuItem.vue
> +    :class="activeSidebarMenu === label ? 'layout__link--active' : null"
Здесь можно сделать намного проще одной строкой. Вот ссылка на (Vue Router)[https://v3.router.vuejs.org/ru/api/#active-class].

2023-03-21 13:23 UTC, S-le commented on src/frontend/src/common/components/SubmitButton.vue
> +    @click="buttonClickHandler"
Тут видимо опечатка

2023-03-21 13:23 UTC, S-le commented on src/frontend/src/layouts/AppLayoutLogo.vue
> +<template>
Для таких компонентов можно писать `template functional`. Вот (ссылка на доку)[https://ru.vuejs.org/v2/guide/render-function.html#%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B].

Кончено, в Vue 3 версии от этого отказались. Поэтому увлекаться этом не стоит, но ознакомиться можно.

2023-03-21 13:23 UTC, S-le commented on src/frontend/src/modules/builder/components/BuilderIngredientsFillingSelector.vue
> +      MAX_INGREDIENTS_NUMBER,
Поскольку значение `MAX_INGREDIENTS_NUMBER` не изменяется, то стоит делаеть его и подобные переменные вычисляемыми свойствами.

2023-03-21 13:23 UTC, S-le commented on src/frontend/src/App.vue
> +    this.$store.dispatch("Builder/init", null, { root: true });
Поскольку у действия нет `payload`, то можно вызывать таким образом `this.$store.dispatch("Builder/init")`. 

`{ root: true }` нужен когда действия вызываются из модуля.

2023-03-21 13:51 UTC, poly-titova commented on src/frontend/src/store/modules/auth.store.js
> +export const resetState = () => ({
можно указать как `getDefaultState` ?

2023-03-21 14:12 UTC, poly-titova commented on src/frontend/src/store/modules/auth.store.js
> +  isAuthorized: false,
_Геттеры предназначены для получения производных от состояния_
я могу менять при этом значение состояния с помощью геттера?

2023-03-21 14:21 UTC, poly-titova commented on src/frontend/src/store/modules/builder.store.js
> +    });
`pizzas` - не уследила, поменяю работу с данными
`module` и `entity` были указанны в примере учебном, вот и прописала

2023-03-22 16:03 UTC, poly-titova commented on src/frontend/src/common/components/FormInput.vue
> +    },
`props: {
  ...
    inputType: {
      type: String,
      default: "",
    },
...
}

<FormInput
      v-for="(formData, dataId) in AUTH_FORM_INPUT_DATA"
      ...
      :inputType="formData.inputType"
     ...
    />
    
   export const AUTH_FORM_INPUT_DATA = [
  {
    ...
    inputType: "email",
    ...
  },
  {
    ...
    inputType: "password",
    ...
  },
];
`
указываю _string_ так как передаётся параметр строки

2023-04-10 14:19 UTC, S-le requested changes
Молодец! Заметно, что ты постаралась и проделала много работы. Все страницы созданы, добавила валидацию, большая часть работы сделана.

Давай исправим последние недочеты. Перед сдачей домашнего задания проверяй работу на соответствие техническому заданию.

Доделай валидацию на странице авторизации. Пользователь должен видеть ошибку, если ввел некорректные данные.

Проработай авторизацию. Пользователь должен логинится и разлогиниться. 

Возникают проблемы с изменением пиццы после нажатия кнопки "Изменить" на странице "Корзина".

Страницы пользователя `/profile` и `/orders` необходимо доделать.

Не унывай, большую часть работы ты уже сделала. Прояви упорство и мы осилим это домашнее задание. Если есть вопросы к комментариям, то пиши мне.

2023-04-10 14:19 UTC, S-le commented on src/frontend/src/common/components/ItemCounter.vue
>      },
Значение `minCount` должно иметь тип _number_, т.к. импользуется в расчетах.

2023-04-10 14:19 UTC, S-le commented on src/frontend/src/common/components/ItemCounter.vue
> +    },
Я понимаю, что можно передавать функции во входные параметры компонента. Однако, по возможности лучше использовать *emit* для передачи данных в родительский компонент. Vue настоятельно рекомендует использовать однонаправленный поток данных. Это значить из родительського в дочерний передаем данные через props. Из дочернего в родительский через emit.

2023-04-10 14:19 UTC, S-le commented on src/frontend/src/common/components/ItemCounter.vue
> +      return "Infinity";
Проверь как объявляется переменная с типом [Infinity](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Infinity).

2023-04-10 14:19 UTC, S-le commented on src/frontend/src/common/components/ItemCounter.vue
>      },
Для чего это вычисляемое свойство? Дополнительную логику оно не добавляет и `count` реактивное значение.

2023-04-10 14:19 UTC, S-le commented on src/frontend/src/common/components/ItemCounter.vue
> +        event.target.value <= MAX_INGREDIENTS_NUMBER
Компонент `ItemCounter.vue` используется в нескольких местах. На странице "Конструктор пиццы", несколько раз на странице "Корзина". На странице "Конструктор пиццы" есть ограничение на максимальное кол-во (3). На странице "Корзина" нет такого ограничения. Следовательно, использование **MAX_INGREDIENTS_NUMBER** нарушит требование ТЗ страницы "Корзина". Если использовать `maxCount`, то это нарушает требование ТЗ страницы "Конструктор пиццы". 

Поэтому, как я уже писал, `max` проще добавить в _props_. Таким образом, `ItemCounter.vue` не будет зависеть от внешнего окружения. А на разных страницах ты будешь передавать, то максимальное значение, которое требуется по ТЗ для страницы.

2023-04-10 14:19 UTC, S-le commented on src/frontend/src/store/modules/cart.store.js
> +    }
Не соответствует ТЗ. Нет ограничение на максимальное количество.

2023-04-10 14:19 UTC, S-le commented on src/frontend/src/common/components/RadioButton.vue
> +      this.inputChangeHandler(updatedValue);
Используй `emit`.

2023-04-10 14:19 UTC, S-le commented on src/frontend/src/modules/auth/components/AuthForm.vue
> +  mixins: [validator],
Validator ты создала и подключила. Молодец! Но его необходимо использовать в компоненте. Ещё раз внимательно проработай урок [3.12. Создание компонентов для создания/редактирования задач](https://up.htmlacademy.ru/vue/1/module/3/item/12)

2023-04-10 14:19 UTC, S-le commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +              $imageWithExtensionLink(user.avatar, '.webp') +
Загляни в `@/static/user.json` у пользователя `"avatar": "/public/img/users/user.jpg"`, а в папке `public/img/users/user5.jpg`. Из-за этого аватар пользователя не отображается.

2023-04-10 14:19 UTC, S-le commented on src/frontend/src/common/components/Sidebar.vue
> +      v-for="(item, id) in Object.values(SIDEBAR_MENU)"
Здесь используй `menu` вместо `SIDEBAR_MENU`.

2023-04-10 14:19 UTC, S-le commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +    ...mapState("Auth", ["user", "isAuthorized"]),
Теперь здесь нужен геттер `isAuthorizes`.

2023-05-28 11:03 UTC, merged